colors.draw_bold_text_with_bright_colors = true
import = [ "~/.config/alacritty/catppuccin/catppuccin-mocha.toml" ]
live_config_reload = true

[env]
TERM = "alacritty"

[window]
dynamic_padding = true
opacity = 0.5
startup_mode = "Maximized"
title = "Alacritty"

[window.padding]
x = 0
y = 0

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 5_000

[font]
size = 12

[font.normal]
family = "Iosevka Term"
style = "Medium"

[font.bold]
family = "Iosevka"
style = "Bold"

[font.italic]
family = "Iosevka"
style = "Italic"

[font.bold_italic]
family = "Iosevka"
style = "Bold Italic"

[font.offset]
x = 0
y = 1

[cursor]
style = "Beam"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

[[keyboard.bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "F11"
mods = "None"
action = "ToggleFullscreen"

[[keyboard.bindings]]
key = "Paste"
mods = "None"
action = "Paste"

[[keyboard.bindings]]
key = "Copy"
mods = "None"
action = "Copy"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "L"
mods = "Control"
chars = "\f"

[[keyboard.bindings]]
key = "PageUp"
mods = "None"
action = "ScrollPageUp"
mode = "~Alt"

[[keyboard.bindings]]
key = "PageDown"
mods = "None"
action = "ScrollPageDown"
mode = "~Alt"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
action = "ScrollToTop"
mode = "~Alt"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
action = "ScrollToBottom"
mode = "~Alt"

