#!/usr/bin/env bash

export BROWSER='brave-beta'
export EDITOR='code'
export TERMINAL='alacritty'

export PATH="$PATH:$(find "${HOME}/.local/bin" -type d | paste -sd ':' -)"
export HISTCONTROL='ignoredups'
export QT_QPA_PLATFORMTHEME='qt5ct'

export XDG_CONFIG_HOME="${HOME}/.config"
export XDG_CACHE_HOME="${HOME}/.cache"
export XDG_DATA_HOME="${HOME}/.local/share"
export INPUTRC="${XDG_CONFIG_HOME}/shell/inputrc"
export XINITRC="${XDG_CONFIG_HOME}/x11/xinitrc"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"